services:
  web:
    build: .
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    volumes:
      - .:/app  # Mounts the current directory to the container's /app directory
    ports:
      - "8000:8000"  # Exposes port 8000 for FastAPI
    environment:
      - PYTHONUNBUFFERED=1  # Ensures logs are printed directly without buffering

